### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by yichuan-w** [aromanro/RayTracer#15]
can you please teach me how to run it

**Comment by aromanro** [comment]
Install Visual Studio: https://visualstudio.microsoft.com/downloads/
Install and build wxWidgets: http://wxwidgets.org/ (depending on the version of the library and where you install it, you might have to adjust the project properties after this, for example the VC++ directories for includes and libraries).
Open RayTracer.sln with Visual Studio.
Be sure 'Release' and 'x64' are selected for build. Build the solution. 
Run the executable, you can do that either separately or directly from Visual Studio.

**Comment by aromanro** [comment]
Before running, check out View | Options. If you read the referred books, you should know what the options are for... some might require looking over the code, though.

**Comment by aromanro** [comment]
Although for now the development version of wxWidgets should work, too, the stable version is the recommended one to be used.
