### ISSUE TITLE
Anisotropic Phong

### ISSUE THREAD

**Issue by i-s-a** [aromanro/RayTracer#2]
Hi, I've been working through the Ray Tracing in One Weekend book. When trying to implement a Anisotropic Phong BRDF I had bugs in my code which I couldn't immediately fix until I saw your project and how you implemented it. I used a few lines from your project to get mine to work. As your project uses the GPL licence, I was wondering if I could have your permission to leave the lines of code in the Anisotropic Phong BRDF, where it looks similar to yours, in my project and release my project under the MIT licence? I've given you credit by linking to your github Ray Tracer project both in the ReadMe file and in the code itself. If you don't mind me releasing under the MIT licence, I'm happy to credit you in any way you like for example by also including a link to your website and your name, whatever you would be happy with. I haven't released it yet until I sort out the licence.

**Comment by aromanro** [comment]
As long as you let that credit in with the link, it's ok.

**Comment by i-s-a** [comment]
Great, Thank You
