### ISSUE TITLE
how to improve it？

### ISSUE THREAD

**Issue by zero000816** [aromanro/RayTracer#4]
![飞船透明](https://user-images.githubusercontent.com/47745171/78629224-fe180200-78c8-11ea-8ad9-da4a681b0b1c.png)
![ironman](https://user-images.githubusercontent.com/47745171/78629251-0e2fe180-78c9-11ea-9a48-07cd2e1e7377.png)

**Comment by aromanro** [comment]
They would benefit from more rays to be able to see better the issues. 

Also adding some description wouldn't hurt. Don't just ask a short question and put images, it's not clear what you really want. Do you want better images? Use more rays. Do you see some problems with the algorithm?

As I mentioned on the blog, the obj loader has issues: https://compphys.go.ro/ray-tracing/
One of them is that it doesn't split the concave polygons correctly. Some obj files might also have non-standard things in them, those won't be loaded properly. Not even the standard ones are perfectly fit, it's just something that works for simple models and that's about it.

**Comment by zero000816** [comment]
thanks so much for your help, i am beginner, i don't know how to put it  best，thank you so much

**Comment by aromanro** [comment]
I would suggest you read the books I pointed out on the blog, or at least the 'in one weekend' one. You can find them here: https://github.com/RayTracing

You'll understand how it works much better.

**Comment by aromanro** [comment]
Since no more questions followed, I'm closing it.

**Comment by zero000816** [comment]
thank you so much，i already know how to solve my problem
  



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Adrian Roman"<notifications@github.com&gt;; 
发送时间: 2020年4月18日(星期六) 凌晨2:35
收件人: "aromanro/RayTracer"<RayTracer@noreply.github.com&gt;; 
抄送: "张三"<1055659897@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [aromanro/RayTracer] how to improve it？ (#4)





 
Since no more questions followed, I'm closing it.
